project_name: eztalk
before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/eztalk
    binary: eztalk
    goos:
      - linux
      - darwin
      - windows
archives:
  - format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - configs/*
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^ci:'
      - '^docs:'
      - '^test:'
release:
  github:
    owner: gowsp
    name: eztalk